"""create empleado

Revision ID: b4b03db735fa
Revises: 
Create Date: 2026-02-13 17:48:34.082085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b03db735fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('idEmpleado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('sueldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('idEmpleado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    # ### end Alembic commands ###
